# -*- coding: utf-8 -*-
"""Antya Alhikmah Alham-UAS Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xa2AqoBreGwzAJ8x8MTvZ9i8ai63GwyX

# **Analisis Deteksi Spam Menggunakan Model LSTM pada Data Twitter Mobil Indonesia**

#Import Data
"""

#Import Modul

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# URL mentah dari file CSV di GitHub
url = 'https://raw.githubusercontent.com/antyaalhikmah/UAS_DeepLearning/main/data-labeling.csv'

# Membaca data dari URL
data = pd.read_csv(url)
data

"""#Preprocessing"""

data.shape

data.info()

# Cek Apakah ada nilai NaN
data.isna().sum()

# Cek data tweet yang terduplikasi
data['tweet'].duplicated().sum()

# Menghapus data tweet yang terduplikasi
data2 = data.drop_duplicates(subset=['tweet'])
data2.shape

# Cek Jumlah Spam Detection
data2['Spam Detection'].value_counts()

# Cek Jumlah Masing-Masing Merek Mobil
data2['entity'].value_counts()

# Visualisasi dataset yang diperlukan
data_tweet = pd.DataFrame(data2['tweet'])
data_tweet.head()

"""##Cleaning

Membersihkan teks dari elemen yang tidak diperlukan, seperti username, emoji, angka, simbol, URL, tag HTML
"""

# Import modul yang diperlukan
import string
import nltk
import re

def remove_URL(tweet): # Menghapus URL
  url = re.compile(r'https?://\S+|www\.\S+')
  return url.sub(r'', tweet)

def remove_html(tweet): # Menghapus tag HTML
  html = re.compile(r'<.*?>')
  return html.sub(r'', tweet)

def remove_emoji(tweet): # Menghapus emoji
  emoji_pattern = re.compile("["
      u"\U0001F600-\U0001F64F"
      u"\U0001F300-\U0001F5FF"
      u"\U0001F680-\U0001F6FF"
      u"\U0001F1E0-\U0001F1FF"
                          "]+", flags=re.UNICODE)
  return emoji_pattern.sub(r'', tweet)

def remove_username(tweet): # Menghapus username
    username_pattern = re.compile(r'@\w+')
    return username_pattern.sub(r'', tweet)

def remove_numbers (tweet): # Menghapus angka
  tweet = re.sub(r'\d+', '', tweet)
  return tweet

def remove_symbols (tweet): # Menghapus simbol
  tweet = re.sub(r'[^a-zA-Z0-9\s]', '', tweet)
  return tweet

# Visualisasi clean dataset 'tweet'
data_tweet['cleaning'] = data_tweet['tweet'].apply(lambda x: remove_URL(x))
data_tweet['cleaning'] = data_tweet['cleaning'].apply(lambda x: remove_html(x))
data_tweet['cleaning'] = data_tweet['cleaning'].apply(lambda x: remove_emoji(x))
data_tweet['cleaning'] = data_tweet['cleaning'].apply(lambda x: remove_username(x))
data_tweet['cleaning'] = data_tweet['cleaning'].apply(lambda x: remove_symbols(x))
data_tweet['cleaning'] = data_tweet['cleaning'].apply(lambda x: remove_numbers(x))

data_tweet.head(10)

"""##Case Folding

Mengubah menjadi huruf kecil semua, untuk mengurangi terjadinya variasi kata karena perbedaan huruf besar dan kecil
"""

def case_folding(text): # Mengubah huruf yang masih uppercase menjadi lowercase
  if isinstance(text, str):
    lowercase_text = text.lower()
    return lowercase_text
  else:
    return text

# Visualisasi Perbandingan dataset
data_tweet['case_folding'] = data_tweet['cleaning'].apply(case_folding)

data_tweet.head(10)

"""##Tokenization

Memecah teks menjadi bagian-bagian yang lebih terstruktur agar memudahkan analisa teks
"""

def tokenize(text):# Fungsi tokenisasi teks
     tokens = text.split()
     return tokens

# Visualisasi Perbandingan dataset
data_tweet['tokenize'] = data_tweet['case_folding'].apply(tokenize)

data_tweet.head(10)

"""##Stopword Removal

Menghapus kata-kata umum yang sering muncul tetapi tidak bermakna pada analisis teks. Contoh: ke, di, dan, dsb.
"""

# Import modul yang dibutuhkan
import requests
from nltk.corpus import stopwords
nltk.download('stopwords')

# Menghapus stopwords
def remove_stopwords(tokens):
    # Membaca stopwords standar bahasa Indonesia dari NLTK
    stop_words = set(stopwords.words('indonesian'))

    # Fungsi untuk menambahkan stopwords dari URL mentah GitHub
    def add_stopwords_from_url(url):
        response = requests.get(url)
        extra_stopwords = response.text.splitlines()
        stop_words.update(extra_stopwords)

    url = 'https://raw.githubusercontent.com/antyaalhikmah/UAS_DeepLearning/main/id.stopwords.txt'

    # Tambahkan stopwords dari URL mentah
    add_stopwords_from_url(url)

    # Menghapus stopwords
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

# Visualisasi perbandingan dataset
data_tweet['stopword_removal'] = data_tweet['tokenize'].apply(remove_stopwords)
data_tweet.head()

!pip install wordcloud matplotlib

import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Gabungkan semua token yang telah difilter menjadi satu string besar
all_words = ' '.join([' '.join(tokens) for tokens in data_tweet['stopword_removal']])

# Membuat WordCloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_words)

# Menampilkan WordCloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('WordCloud dari Tweet setelah Penghapusan Stopwords')
plt.show()

"""##Stemming

Mengubah kata-kata pada teks menjadi bentuk dasar (root form), untuk mengurangi variasi kata dari perubahan bentuk yang berbeda sehingga kata-kata dengan makna yang sama dianggap entitas yang sama. Misalnya, "berjalan", "jalan-jalan", "jalan", dan "pejalan" semuanya direduksi menjadi "jalan"
"""

# Install dan Import modul yang diperlukan
!pip install Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.stem import PorterStemmer
from nltk.stem.snowball import SnowballStemmer

# Membuat instance dari StemmerFactory
factory = StemmerFactory()

# Membuat instance stemmer menggunakan factory
stemmer = factory.create_stemmer()

# Mendefinisikan fungsi stem_text untuk melakukan stemming pada teks input
def stem_text(text):
    return [stemmer.stem(word) for word in text]

# Visualisasi perbandingan dataset
data_tweet['stemming'] = data_tweet['stopword_removal'].apply(lambda x: ' '.join(stem_text(x)))
data_tweet.head(10)

df = data_tweet.copy()  # Menyalin df_tweet untuk membuat dfEDA
df['entity'] = data['entity']
df['Spam Detection'] = data['Spam Detection']
df.head(10)

#save data setelah di EDA
df.to_csv('Data-EDA.csv',encoding='utf8',index=False)

"""#EDA

##Data Visualization
"""

#frekuensi spam detection
df['Spam Detection'].value_counts()

# Menghitung jumlah sentimen per entitas
sentiment_count = df.groupby(['entity', 'Spam Detection']).size().unstack(fill_value=0)

# Membuat plot
plt.figure(figsize=(10, 6))

# Plotting
sentiment_count.plot(kind='bar', figsize=(10, 6))

plt.title('Spam Detection Berdasarkan Merek Mobil')
plt.xlabel('Merek Mobil')
plt.ylabel('Jumlah')
plt.xticks(rotation=45)
plt.legend(title='Spam Detection')
plt.tight_layout()

# Menampilkan plot
plt.show()

"""Grafik di atas menunjukkan deteksi spam berdasrkan merek mobil dengan dua kategori yaitu spam, dan ham (non-spam).
*   Jumlah pesan spam yaitu 1355, lebih
banyak dibandingkan dengan jumlah pesan ham yaitu 743.
*   Merek Daihatsu, Toyota, dan Suzuki  memiliki jumlah pesan spam tertinggi.
*   Beberapa merek seperti Audi, BMW, Mazda, dan Mercedes memiliki jumlah pesan yang sangat rendah, baik untuk spam maupun ham.
*   Deteksi spam bervariasi cukup signifikan antara merek-merek mobil, dengan beberapa merek seperti Daihatsu dan Toyota memiliki tingkat spam yang jauh lebih tinggi.
"""

!pip install nltk
import nltk
nltk.download('punkt')

# Import Modul yang dibutuhkan
from nltk.util import ngrams
from collections import Counter
import nltk # Import nltk

def get_ngrams(text, n):
    tokens = nltk.word_tokenize(text.lower())
    n_grams = ngrams(tokens, n)
    return n_grams

def get_ngram_frequencies(df, n):
    all_ngrams = []
    # Assuming 'Tweet' is the column containing the text data
    for text in df['tweet']: # Replace 'Tweet' with the actual column name if it's different
        ngrams = get_ngrams(text, n)
        all_ngrams.extend(ngrams)
    return Counter(all_ngrams)

# Menghitung unigram, bigram, dan trigram
unigram_freq = get_ngram_frequencies(df, 1)
bigram_freq = get_ngram_frequencies(df, 2)
trigram_freq = get_ngram_frequencies(df, 3)

print("Unigram Frequencies:")
print(unigram_freq.most_common(10))  # Menampilkan 10 unigram teratas

print("\nBigram Frequencies:")
print(bigram_freq.most_common(10))  # Menampilkan 10 bigram teratas

print("\nTrigram Frequencies:")
print(trigram_freq.most_common(10))  # Menampilkan 10 trigram teratas

"""Output diatas untuk menunjukkan frekuensi unigram, bigram, serta trigram yang juga dapat digunakan untuk mendeteksi spam
*  Banyak tweet yang menyebutkan merek mobil, khususnya Toyota, Honda, dan Suzuki.
*   Penggunaan hashtag dan mention akun cukup tinggi dalam tweet-tweet ini.
*   Ada banyak penggunaan tanda baca seperti koma, titik, tanda tanya, dan tanda seru, menunjukkan beragamnya gaya penulisan dan emosi dalam tweet.
*  Beberapa pola menunjukkan penggunaan fitur terjemahan atau kampanye khusus, terutama yang terkait dengan merek Suzuki.




"""

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# Get unique entities
entities = df['entity'].unique()

# Create wordclouds for each entity and sentiment
for entity in entities:
    # Filter DataFrame for entity and sentiments
    df_ham = df[(df['entity'] == entity) & (df['Spam Detection'] == 'ham')]
    df_spam = df[(df['entity'] == entity) & (df['Spam Detection'] == 'spam')]

    # Convert 'stemming' column to strings
    df_ham['stemming'] = df_ham['stemming'].astype(str)
    df_spam['stemming'] = df_spam['stemming'].astype(str)

    # Create text for wordclouds if there are words, otherwise set to None to skip
    text_ham = ' '.join(df_ham['stemming']) if not df_ham.empty else None
    text_spam = ' '.join(df_spam['stemming']) if not df_spam.empty else None

    # Create wordclouds if text is not None
    stopwords = set(STOPWORDS)
    if text_ham:
        wordcloud_ham = WordCloud(width=800, height=800, background_color='white', stopwords=stopwords, min_font_size=10).generate(text_ham)
    if text_spam:
        wordcloud_spam = WordCloud(width=800, height=800, background_color='white', stopwords=stopwords, min_font_size=10).generate(text_spam)

    # Plot wordclouds if they were generated
    plt.figure(figsize=(16, 8), facecolor=None)
    plt.suptitle(f"Wordclouds: {entity}", fontsize=16)

    if text_ham:
        plt.subplot(1, 2, 1)
        plt.imshow(wordcloud_ham)
        plt.axis("off")
        plt.title("ham")

    if text_spam:
        plt.subplot(1, 2, 2)
        plt.imshow(wordcloud_spam)
        plt.axis("off")
        plt.title("spam")

    plt.tight_layout(pad=3.0)
    plt.show()

"""1. Daihatsu
* spam : "saldo", "astrapay", "sahabat", "daihatsu", "indonesia"

Pesan spam pada daihatsu banyak membahas terkait sayembara, promosi, serta pesan berulang terkait daihatsu indonesia

* ham : "daihatsu", "indonesia", "post", "produk", "master"

Pesan ham pada daihatsu banyak membahas terkait daihatsu indonesia itu sendiri tetapi yang benar adanya membahas produk, fitur dll


2. Mitsubishi
* spam : "pajero", "mitsubishi", "lindas", "celaka", "tragis"

Pesan spam pada mitsubishi banyak membahas terkait berita kecelakaan atau kasus yang lumayan banyak berkaitan dengan merek mobil mitsubishi itu sendiri, dan pesan tersebut dikirim dengan akun berita yang berbeda berulang kali

* ham : "mitsubishi", "mobil", "post", "xpander", "harga"

Pesan ham pada mitsubishi banyak membahas terkait merek mobil mitsubishi, harga, fitur, yang bukan berasal dari admin atau buzzer

3. Suzuki
* spam : "suzukitemanberkendara", "smartmove", "thread", "spam", "yourgeartranslate"

Pesan spam pada suzuki banyak dari akun suzuki itu sendiri terkait hashtag yang suzuki punya, biasanya berhubungan dengan promo atau sayembara

* ham : "mobil", "suzuki", "post", "ban", "beli", "mesin"

Pesan spam pada suzuki banyak membahas terkait fitur, harga dari produk mobil suzuki itu sendiri

4. Toyota
* spam : "shopee", "live", "flash", "sale", "mobil", "celaka"

Pesan spam pada toyota banyak membahas terkait sayembara, promosi, kecelakaan yang berhubungan dengan merek toyota

* ham : "harga", "lengkap", "kendara", "produk", "master"

Pesan ham pada daihatsu banyak membahas terkait toyota  itu sendiri tetapi yang benar adanya membahas produk, fitur dll

#Modelling LSTM
"""

#import modul yang dibutuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import BertTokenizer

from sklearn.utils import resample

# Menghitung jumlah data 'Spam'
ham_count = df[df['Spam Detection'] == 'ham'].shape[0]

# Melakukan undersampling pada data 'Ham' agar jumlahnya sama dengan jumlah data 'Spam'
spam_undersampled = resample(df[df['Spam Detection'] == 'spam'],
                            replace=False, # Allow sampling with replacement
                            n_samples=ham_count,
                            random_state=42)

# Menggabungkan data hasil undersampling 'Ham' dengan data asli 'Spam'
df_undersampled = pd.concat([spam_undersampled, df[df['Spam Detection'] == 'ham']])

# Mengacak DataFrame
df_undersampled = df_undersampled.sample(frac=1, random_state=42)

df_undersampled['Spam Detection'].value_counts()

data_model = df_undersampled[['stemming', 'Spam Detection']]
data_model.head()

# Convert sentiment labels to numeric values
label_encoder = LabelEncoder()
data_model['Spam Detection'] = label_encoder.fit_transform(data_model['Spam Detection'])

# Splitting the data into train and test sets with a ratio of 80:20
train_data, test_data = train_test_split(data_model, test_size=0.2, random_state=1507)

# Define a custom dataset
class TweetDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels
        self.tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts.iloc[idx]
        label = self.labels.iloc[idx]
        tokens = self.tokenizer.encode(text, add_special_tokens=True)
        return torch.tensor(tokens), torch.tensor(label)

# Tokenize and create DataLoader
def collate_fn(batch):
    texts, labels = zip(*batch)
    texts_padded = pad_sequence(texts, batch_first=True, padding_value=0)
    labels = torch.tensor(labels)
    return texts_padded, labels

# Create datasets
train_dataset = TweetDataset(train_data['stemming'], train_data['Spam Detection'])
test_dataset = TweetDataset(test_data['stemming'], test_data['Spam Detection'])

# Create DataLoader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, collate_fn=collate_fn)

# Define the LSTM model
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size, output_size, num_layers=1):
        super(LSTMModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
        self.num_layers = num_layers # store num_layers as an attribute
        self.hidden_size = hidden_size # store hidden_size as an attribute

    def forward(self, x):
        x = self.embedding(x)
        # Initialize hidden state with correct shape
        h_0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c_0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        out, _ = self.lstm(x, (h_0, c_0))
        out = self.fc(out[:, -1, :])
        return out

# Hyperparameters
vocab_size = len(BertTokenizer.from_pretrained('bert-base-uncased').vocab)
embed_size = 512
hidden_size = 512
output_size = len(label_encoder.classes_)
num_layers = 5
num_epochs = 20
learning_rate = 0.001

# Instantiate the model, loss function, and optimizer
model = LSTMModel(vocab_size, embed_size, hidden_size, output_size, num_layers)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training the model
model.train()
for epoch in range(num_epochs):
    for texts, labels in train_loader:
        outputs = model(texts)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Assuming 'model' is your trained model and 'optimizer' is your optimizer
torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,
            }, 'Spam_Detection_predict_model.pth')

import torch.quantization

# Assuming 'model' is your trained model
quantized_model = torch.quantization.quantize_dynamic(
    model, {torch.nn.Linear}, dtype=torch.qint8
)

# Save the quantized model
torch.save(quantized_model.state_dict(), 'prediction_model.pth')

"""File Model
https://drive.google.com/drive/folders/1TudmCwPTS7BCGzc5U1sB03QnhIAibcwD?usp=sharing

Github:
https://github.com/antyaalhikmah/UAS_DeepLearning
"""

# Testing the model
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for texts, labels in test_loader:
        outputs = model(texts)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print(f'Test Accuracy: {100 * correct / total:.2f}%')